customdb:
  enabled: false                                   # Enable/disable custom database support. Leave this disabled if using a script such as phpBB.
  autocreate: true                                 # Enable/disable automatic creation of the database tables and columns for a custom database.
  table: authdb_users                              # Table name to use for your custom database.
  userfield: username                              # Field/column name to use for storing user names.
  passfield: password                              # Field/column name to use for storing user passwords.
  emailfield: email                                # Field/column name to use for storing user email addresses. Leave blank to disable email requirement.
  encryption: md5                                  # Encription type to use for password hashing. Options are MD5, SHA1, and SHA512.
register:
  enabled: true                                    # Enable/disable allowing users to register.
  force: true                                      # Enable/disable forcing users to register.
  delay: 4 seconds                                 # Amount of time 
  timeout: 3 minutes                               # 
login:
  enabled: true                                    # REMOVE???
  method: prompt                                   # Set to normal to use /login password method or prompt for password input only.
  delay: 4 seconds                                 # 
  timeout: 3 minutes                               # Amount of time a player has to login before the configured action is taken.
  tries: 3                                         # Number of allowed incorrect password tries.
  action: kick                                     # Action to perform when a maximum number of password tries is reached. Currently only option is kick.
link:
  enabled: true                                    # 
  rename: true                                     # 
unlink:
  enabled: true                                    # 
  rename: true                                     # 
username:
  minimum: 3                                       # 
  maximum: 16                                      # 
password:
  minimum: 6                                       # 
  maximum: 16                                      # 
session:
  enabled: true                                    # 
  start: login                                     # 
  length: 1 hour                                   # 
  protect: true                                    # 
guest:
  commands: false                                  # 
  chat: false                                      # 
  building: false                                  # 
  destruction: false                               # 
  movement: false                                  # 
  interactions: false                              # 
  inventory: false                                 # 
  drop: false                                      # 
  pickup: false                                    # 
  health: false                                    # 
  pvp: false                                       # 
  mobtargeting: false                              # 
  mobdamage: false                                 # 
protection:
  notify: true                                     # Enable/disable protection messages sent to players.
  delay: 3 seconds                                 # Amount of time before protection messages can be sent to players again.
filter:
  action: kick                                     # Action to perform when a username matches the filter. Options are kick and rename.
  username: "`~!@#$%^&*()-=+{[]}|\\:;\"<,>.?/ "    # Characters and symbols to check for in usernames. We recommend leaving this as is.
  password: "&"                                    # Characters and symbols to check for in passwords. We recommend leaving this as is.
  whitelist: Contex,Wulfspider                     # Usernames to exclude from username and password filtering.
