CraftIRC:
  enabled: false                                   # Enable/disable extended features and support for CraftIRC.
  tag: admin                                       # Channel tag to use for messages sent using CraftIRC.
  prefix: "%b%%green%[{PLUGIN}]%k%%b%"             # Prefix format and coloring for displaying messages in CraftIRC.
