name: AuthDB
main: com.authdb.AuthDB
version: dev-SNAPSHOT
website: http://www.authdb.com
description: Provides script and custom database user authentication through MySQL.
authors:
  - CraftFire
  - Contex
  - Wulfspider
commands:
  register:
    description: Register for an account.
    usage: /<command> <password> <email>
  login:
    description: Login to your account.
    usage: /<command> <password>
  logout:
    description: Logout yourself or specified player.
    usage: /<command> <player>
  setspawn:
    description: Set spawn locations for guests and registered players.
    usage: /<command> <group>
  authdb:
    description: Set of commands to reload, show version, and more.
    usage: /<command> <extra>
