name: AuthDB
main: com.authdb.AuthDB
version: "${project.version}"
website: http://www.authdb.com
database: true
description: Script and custom database user authentication through MySQL.
authors:
  - CraftFire
  - Contex
  - Wulfspider
commands:
  register:
    description: Register for an account.
    usage: /<command> <password> <email>
  login:
    description: Login to your account.
    usage: /<command> <password>
  logout:
    description: Logout yourself or specified player.
    usage: /<command> <player>
  link:
    description: Links you to another account.
    usage: /<command> <player> <password>
  unlink:
    description: Unlinks you from the other account.
    usage: /<command> <player> <password>
  setspawn:
    description: Set spawn locations for guest and registered player groups.
    usage: /<command> <group>
  authdb:
    description: Set of commands to reload, show version, and more.
    usage: /<command> <extra>
