name: AuthDB
version: 2.3.0.${build.number}
description: Script and custom database user authentication through MySQL.
authors: [CraftFire, Contex, Wulfspider]
website: http://www.authdb.com

main: com.authdb.AuthDB
database: true
softdepend: [Spout, CraftIRC]

commands:
  register:
    description: Register for an account.
    permission: authdb.command.user.register
    usage: /<command> password email
  login:
    description: Login to your account.
    permission: authdb.command.user.login
    usage: /<command> password
  logout:
    description: Logout yourself or specified player.
    permission: authdb.command.user.logout
    usage: /<command> player
  link:
    description: Links you to another account.
    permission: authdb.command.user.link
    usage: /<command> player password
  unlink:
    description: Unlinks you from the other account.
    permission: authdb.command.user.unlink
    usage: /<command> player password
#  setspawn:
#    description: Set spawn locations for guest and registered player groups.
#    permission: authdb.command.user.setspawn
#    usage: /<command> group
  authdb:
    description: Set of commands to reload, show version, and more.
    usage: /<command> <extra>

permissions:
  authdb.command.user.*:
    description: Placeholder
    children:
      authdb.command.user.register: true
      authdb.command.user.unregister: true
      authdb.command.user.login: true
      authdb.command.user.logout: true
      authdb.command.user.link: true
      authdb.command.user.unlink: true
      authdb.command.user.password: true
      authdb.command.user.email: true
      authdb.command.user.users: true
  authdb.command.user.register:
    description: Placeholder
    default: true
#  authdb.command.user.unregister:
#    description: Placeholder
#    default: true
  authdb.command.user.login:
    description: Placeholder
    default: true
  authdb.command.user.logout:
    description: Placeholder
    default: true
  authdb.command.user.link:
    description: Placeholder
    default: true
  authdb.command.user.unlink:
    description: Placeholder
    default: true
#  authdb.command.user.password:
#    description: Placeholder
#    default: true
#  authdb.command.user.email:
#    description: Placeholder
#    default: true
  authdb.command.user.users:
    description: Placeholder
    default: true
#  authdb.command.admin.unregister:
#    default: op
  authdb.command.admin.*:
    children:
      authdb.command.admin.login: true
      authdb.command.admin.logout: true
      authdb.command.admin.password: true
      authdb.command.admin.email: true
      authdb.command.admin.reload: true
  authdb.command.admin.login:
    description: Placeholder
    default: op
  authdb.command.admin.logout:
    description: Placeholder
    default: op
  authdb.command.admin.password:
    description: Placeholder
    default: op
#  authdb.command.admin.email:
#    description: Placeholder
#    default: op
  authdb.command.admin.reload:
    description: Placeholder
    default: op
