Core:
  plugin:
    debugmode: false
    usagestats: true
  database:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: root
    name: forum
    prefix: phpbb_
    keepalive: false
  script:
    name: phpBB
    version: 3.0.8
  customdb:
    enabled: false
    autocreate: true
    table: authdb_users
    userfield: username
    passfield: password
    emailfield: email
    encryption: md5
  register:
    enabled: true
    force: true
/    delay: 2 seconds
/    show: 10 seconds
/    timeout: 3 minutes
  login:
    method: prompt
    action: kick
    tries: 3
    kick: true
    delay: 2 seconds
    show: 10 seconds
    timeout: 3 minutes
  link:
    enabled: true
    rename: true
  unlink:
    enabled: true
    rename: true
  username:
    minimum: 3
    maximum: 16
  password:
    minimum: 6
    maximum: 16
  session:
    start: login
/   length: 1 hour
    time: minutes
    length: 60
    protect: true
  idle:
    time: seconds
    length: 30
    kick: true
    whitelist: Contex,Wulfspider
  guest:
    commands: false
    chat: false
    building: false
    destruction: false
    movement: false
    interactions: false
    inventory: false
    drop: false
    pickup: false
    health: false
    pvp: false
    mobtargeting: false
    mobdamage: false
  filter:
/    action: kick
    username: "`~!@#$%^&*()-=+{[]}|\\:;\"<,>.?/ "
    password: "&"
    whitelist: Contex,Wulfspider

Plugins:
  CraftIRC:
    enabled: false
    tag: admin
    prefix: "%b%%green%[{PLUGIN}]%k%%b%"
