name: AuthDB
version: 1.4
main: com.gmail.contexmoh.authdb.AuthDB
website: https://github.com/contex/AuthDB/
description: Enables Minecraft server authentication through an external authentication method (such as Joomla, phpBB3, OpenID, and so on)
authors:
    - Contex
    - Wulfspider
commands:
    register:
        description: Register an account with your username.
        usage: /<command> <password> <email>
    login:
        description: Login to your username.
        usage: /<command> <password>