name: AuthDB
main: com.authdb.AuthDB
version: 2.3.0
website: http://www.authdb.com
description: Provides script and custom database user authentication through MySQL.
authors:
  - CraftFire
  - Contex
  - Wulfspider
commands:
  login:
    description: Login to your account.
    usage: /<command> <password>
  register:
    description: Register for an account.
    usage: /<command> <password> <email>